hwc: fix unused variable error [1/1]
PD#SWPL-139173

Problem:
user build
error: unused variable 'outstride'
error: unused variable 'instride'

Solution:
remove unused variable

Verify:
ohm

Change-Id: Ib0542c0dad2d2f29924aaf04800a47c7333f79d1
Signed-off-by: Cheng Wang2 <cheng.wang2@amlogic.com>